// Copyright (c) 2026 Antoine Veillé
// SPDX-License-Identifier: CC-BY-SA-4.0

import { Button, LineEdit, TextEdit, TextEdit, TextEdit, HorizontalBox } from "std-widgets.slint";
import { Header } from "../design//header.slint";
export component EditEngineDialog inherits Rectangle {
    in-out property <bool> open;
    in property <string> name;
    in property <string> executable;
    in property <image> icon-engine;
    in property <string> icon-path;
    visible: root.open;
    callback save_option();
    callback cancel_option();
    width: 800px;
    height: 800px;


    //name of engine
    Text {
        height: 27px;
        text: "Name";
        font-size: 20px;
        x: 66px;
        y: 171px;
    }
    LineEdit {
        height: 30px;
        font-size: 24px;
        text: root.name;
        y: 209px;
        x: 60px;
        width: 350px;

    }

    //executable path
    Text {
        text: "Executable path";
        font-size: 20px;
        y: 328px;
        x: 64px;
    }
    LineEdit {
        font-size: 20px;
        height: 30px;
        text: root.executable;
        y: 366px;
        width: 350px;
        x: 60px;
    }

    //icon path
    Text {
        text: "Icon path";
        font-size: 20px;
        y: 428px;
        x: 64px;
    }

    TouchArea {
        height: 128px;
        width: 123px;
        y: 424px;
        x: 432px;
        Rectangle {
            border-color: #ffffff;
            height: 64px;
            y: 432px;
            width: 69px;
            x: 410px;
        }
        Image {
            source: root.icon-engine;
            height: 40px;
            y : 458px;
            width: 40px;
            x: 420px;
        }
    }
    LineEdit {
        font-size: 20px;
        height: 30px;
        text: root.icon-path;
        y: 466px;
        width: 350px;
        x: 60px;
    }


    Button {
        text: "Change path";
        y: 466px;
        x: 417px;
    }


    //save and cancel
    Button {
        text: "Save";
        width: 65px;
        y: 552px;
        x: 638px;
        clicked => {
            root.save_option();
        }
    }
    Button {
        text: "Cancel";
        width: 65px;
        y: 552px;
        x: 711px;
        clicked => {
            root.cancel_option();
        }
    }
}