import { Button, ComboBox } from "std-widgets.slint";

export component EngineSelector inherits Rectangle {

    callback add();
    callback remove();
    callback option();
    in property <[string]> engines;
    visible: true;
    in-out property <int> selected-engine;
    Text {
        text: "Engines";
        y: 16px;
        x: 13px;
        font-size: 30px;
    }
    ComboBox {
        x: 11px;
        y: 55px;
        width: 594px;
        height: 65px;

        model: root.engines;
        current-index: root.selected-engine;

        changed current-index => {
            root.selected-engine = self.current-index;
        }
    }

    Button {
        text: "Add";
        width: 68px;
        x: 612px;
        y: 47px;

        clicked => {
            root.add();
        }
    }

    Button {
        text: "Remove";
        width: 68px;
        x: 611px;
        y: 85px;

        clicked => {
            root.remove();
        }
    }

    Button {
        text: "Option";
        x: 686px;
        y: 84px;
        visible: false;
        clicked => {
            root.option();
        }
    }
}