// Copyright (c) 2026 Antoine Veillé
// SPDX-License-Identifier: CC-BY-SA-4.0

import { Header } from "header.slint";
import { EngineSelector } from "engine-selector.slint";
import { BottomBar } from "bottom-bar.slint";
import { EditEngineDialog } from "edit-engine-dialog.slint";

export component MainWindow inherits Window {
    callback cancel_option();
    callback save_option();
    callback option();
    callback launch();
    callback remove_engine();
    callback add_engine();
    in property <bool> option_open;
    in property <[string]> engines;
    in-out property <int> selected-engine;

    //option engines
    in property <string> executable;
    in property <string> name_engine;
    in property <image> icon-engine;
    in property <string> icon-path;

    width: 800px;
    height: 600px;

    title: "DoomLauncher";
    icon: @image-url("../icon.png");

    Header {

    }
    EditEngineDialog {
        visible: option_open;
        cancel_option => {
            root.cancel_option();
        }
        save_option => {
            root.save_option();
        }
        executable: root.executable;
        name: root.name_engine;
        icon-engine: root.icon-engine;
        icon-path: root.icon-path;

    }
    EngineSelector {

        x: 0px;
        y: 184px;
        visible: !option_open;
        engines: root.engines;

        selected-engine <=> root.selected-engine;
        add => {
            root.add_engine();
        }
        remove => {
            root.remove_engine();
        }
        option => {
            root.option();
        }
    }

    BottomBar {

        x: 0px;
        y: 552px;

        launch => {
            root.launch();
        }
        visible: !option_open;
    }
}