import { Header } from "header.slint";
import { EngineSelector } from "engine-selector.slint";
import { BottomBar } from "bottom-bar.slint";
import { EditEngineDialog } from "edit-engine-dialog.slint";

export component MainWindow inherits Window {
    callback cancel_option();
    callback option();
    callback launch();
    callback remove_engine();
    callback add_engine();
    in property <bool> option_open;
    in property <[string]> engines;
    in-out property <int> selected-engine;

    width: 800px;
    height: 600px;

    title: "DoomLauncher";
    icon: @image-url("../icon.png");

    Header {
        x: 64px;
        y: 27px;
    }
    EditEngineDialog {
        visible: option_open;
        cancel_option => {
            root.cancel_option();
        }
    }
    EngineSelector {

        x: 0px;
        y: 184px;
        visible: !option_open;
        engines: root.engines;

        selected-engine <=> root.selected-engine;

        add => {
            root.add_engine();
        }

        remove => {
            root.remove_engine();
        }

        option => {
            root.option();
        }
        Text {
            text: selected-engine;
        }
    }

    BottomBar {

        x: 0px;
        y: 552px;

        launch => {
            root.launch();
        }
        visible: !option_open;
    }
}